### PR TITLE
Sync acks

### PR DESCRIPTION
**Pull request by efrederic**
Should we switch the block size back to 134217728 before merging?

### CODE REVIEW

**Comment by Vegetable26** [comment]
Yah, that'd probably make sense. We should probably make a task for supporting variable size blocks in the future too.

**Comment by pelmers** [comment]
```
vagrant@vagrant:~$ hdfs dfs -fs hdfs://localhost:5351 -copyFromLocal mangos /m
2016-11-10 15:29:31,496 WARN hdfs.DataStreamer: Exception for 0:blk_1245955772757763287_1
java.io.IOException: ResponseProcessor: Expecting seqno  for block 0:blk_1245955772757763287_11 but received 32
    at org.apache.hadoop.hdfs.DataStreamer$ResponseProcessor.run(DataStreamer.java:1035)
copyFromLocal: All datanodes [DatanodeInfoWithStorage[127.0.0.1:50010,null,DISK]] are bad. Aborting...
```

**Comment by pelmers** [comment]
here mangos is 2.9m, block size is default 130m.
it doesn't always fail at seqno 32, sometimes earlier or later

**Comment by Vegetable26** [comment]
Sounds racy, especially with the nondeterministic fails and large block size.

**Pull request merged**
